version: '3.8'

services:
  redis:
    container_name: ingress_redis_cache
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgres:
    container_name: ingress_postgres_db
    image: postgres:latest
    environment:
      POSTGRES_DB: ingress_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ingress
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    container_name: ingress_rabbitmq
    image: rabbitmq:management
    ports:
      - "5672:5672" #  RabbitMQ port
      - "15672:15672" # rabbit management ui port
    environment:
      RABBITMQ_DEFAULT_USER: ingress
      RABBITMQ_DEFAULT_PASS: ingress

volumes:
  redis_data:
  postgres_data: